-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 17:47:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_doctesis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_doctesis` ;

-- -----------------------------------------------------
-- Schema bd_doctesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_doctesis` DEFAULT CHARACTER SET utf8mb4;
USE `bd_doctesis` ;

-- -----------------------------------------------------
-- Table `bd_doctesis`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_doctesis`.`documento` ;

CREATE TABLE IF NOT EXISTS `bd_doctesis`.`documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `autores` VARCHAR(255) NULL DEFAULT NULL,
  `resumen` VARCHAR(1000) NULL DEFAULT NULL,
  `anio_publicacion` INT NULL DEFAULT NULL,
  `asesor` VARCHAR(100) NULL DEFAULT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `tema` VARCHAR(100) NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  `updated_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_doctesis`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_doctesis`.`roles` ;

CREATE TABLE IF NOT EXISTS `bd_doctesis`.`roles` (
  `id` INT NOT NULL,
  `nombre_rol` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `nombre_rol` ON `bd_doctesis`.`roles` (`nombre_rol` ASC);


-- -----------------------------------------------------
-- Table `bd_doctesis`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_doctesis`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `bd_doctesis`.`usuarios` (
  `id` INT NOT NULL,
  `correo_corporativo` VARCHAR(100) NULL DEFAULT NULL,
  `rol` VARCHAR(50) NOT NULL,
  `roles_id` INT NOT NULL,
  `documento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `bd_doctesis`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_documento1`
    FOREIGN KEY (`documento_id`)
    REFERENCES `bd_doctesis`.`documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `correo_corporativo` ON `bd_doctesis`.`usuarios` (`correo_corporativo` ASC);

CREATE INDEX `fk_usuarios_roles1_idx` ON `bd_doctesis`.`usuarios` (`roles_id` ASC);

CREATE INDEX `fk_usuarios_documento1_idx` ON `bd_doctesis`.`usuarios` (`documento_id` ASC);


-- -----------------------------------------------------
-- Table `bd_doctesis`.`log_accesos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_doctesis`.`log_accesos` ;

CREATE TABLE IF NOT EXISTS `bd_doctesis`.`log_accesos` (
  `id` INT NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `fecha_ingreso` DATETIME NULL DEFAULT NULL,
  `direccion_ip` VARCHAR(50) NULL DEFAULT NULL,
  `navegador` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad_acceso` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `log_accesos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_doctesis`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `id_usuario` ON `bd_doctesis`.`log_accesos` (`id_usuario` ASC);

--
-- Dumping data for table `roles`
--

LOCK TABLES `roles` WRITE;
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` VALUES (1,'Administrador'),(5,'Asesor'),(4,'Estudiante'),(3,'Monitor'),(2,'Revisor');
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `usuarios`
--

LOCK TABLES `usuarios` WRITE;
/*!40000 ALTER TABLE `usuarios` DISABLE KEYS */;
/*!40000 ALTER TABLE `usuarios` ENABLE KEYS */;
UNLOCK TABLES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
